# Generated by Django 3.0.6 on 2020-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Like', 'Like'), ('Angry', 'Angry'), ('Dislike', 'Dislike'), ('Funny', 'Funny')], default='Like', max_length=8),
        ),
    ]
