# Generated by Django 3.0.6 on 2020-07-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200727_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='person',
            new_name='make_comment',
        ),
    ]
